odom_model_type: "diff"
odom_alpha5: 0.1
transform_tolerance: 0.2
gui_publish_rate: 10.0
laser_max_beams: 50
min_particles: 500
max_particles: 1500
kld_err: 0.05
kld_z: 0.99
odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.8
odom_alpha4: 0.2
laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_lambda_short: "0.1
laser_model_type: "likelihood_field"
laser_likelihood_max_dist: 4.0
update_min_d: 0.0
update_min_a: 0.01
resample_interval: 1
use_map_topic: True
first_map_only: True
tf_broadcast: True
odom_frame_id: "odom"
base_frame_id: "base_link"
global_frame_id: "map"
resample_interval: 1
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.1

initial_pose_x: 0.0
initial_pose_y: value="0.0
initial_pose_a: value="0.0
initial_cov_xx: value="0.25
initial_cov_yy: value="0.25
initial_cov_aa: value="0.2
